feat: Adding web-threejs library to sdk
inworld-ai/inworld-web-sdk pull request #108
Opened 2023-12-12 23:14 UTC by Disfractal

## Description

feat: Added the new Three.js module to the web sdk
fix: Updated root .gitignore for new files

## Related Ticket (for Inworld.ai developers)

https://inworldai.atlassian.net/jira/software/c/projects/CORE/boards/8?quickFilter=26&selectedIssue=CORE-4705

2023-12-14 00:11 UTC, tshashkova requested changes
Add new package to ISSUE_TEMPLATE files too

2023-12-14 00:11 UTC, tshashkova commented on packages/web-threejs/src/innequin/Innequin.ts
> +    console.log('Innequin - Character Loaded.');
Maybe you add debug option for all console.log which are present in package
What do you think?
It's nice to understand the loading progress, but it should be up to developer needs

2023-12-14 00:11 UTC, tshashkova commented on packages/web-threejs/src/innequin/animator/utils/InnequinPhonemesToViseme.ts
> +// eslint-disable-next-line @typescript-eslint/no-unused-vars
Let's check that eslint-disable is used only it's impossible to compile application without these comments
For example, seems here  you just don't use EXPRESSION_FACTOR and EXPRESSION_FACTOR. And this variables can be removed at all

2023-12-14 00:11 UTC, tshashkova commented on packages/web-threejs/src/rpm/RPM.ts
> +    if (this.animator && this.animator.animatorReady) {
Just simplify
`if (this.animator?.animatorReady) {}`

2023-12-15 15:22 UTC, Disfractal commented on packages/web-threejs/package.json
> +    "eslint-plugin-prettier": "^4.2.1",
Removed all dependencies common

2023-12-15 15:28 UTC, Disfractal commented on packages/web-threejs/.npmignore
> +EXTENSIONS.md
Is it the imgs folder and readme? I'm not sure what a pack for NPM would consist of.

2023-12-15 15:34 UTC, Disfractal commented on packages/web-threejs/src/innequin/Innequin.ts
> +    console.log('Innequin - Character Loaded.');
Ya I thought about this as well. Maybe an enviroment var which is false by default.

2023-12-20 17:01 UTC, tshashkova commented on packages/web-threejs/.npmignore
> +EXTENSIONS.md
README, yes
And images if it's required part of package
So, I believe everything is correct from your side, JIC

2023-12-20 17:21 UTC, tshashkova commented
@Disfractal If you're not ready to add tests right now, it's better to exclude them at all for your package
I mean not pass option ( --passWithNoTests), just remove **yarn test** command call from your package (release-it)

2023-12-21 20:40 UTC, Disfractal commented
> @Disfractal If you're not ready to add tests right now, it's better to exclude them at all for your package I mean not pass option ( --passWithNoTests), just remove **yarn test** command call from your package (release-it)

Originally yarn test wasn't included in the package.json but when I added it with --passWithNoTests I got this error:
> @inworld/web-threejs
error Command "test" not found. Did you mean "jest"?

2024-01-02 21:03 UTC, tshashkova approved these changes

2024-01-03 23:32 UTC, merged